import streamlit as st
from openai import OpenAI, AssistantEventHandler
from typing_extensions import override

# --- INITIALIZATION ---
st.set_page_config(page_title="RAG Agent Chatbot", layout="centered")

# Load credentials from secrets
client = OpenAI(api_key=st.secrets["OPENAI_API_KEY"])
ASSISTANT_ID = st.secrets["ASSISTANT_ID"]

# Initialize session state
if "messages" not in st.session_state:
    st.session_state.messages = []
if "thread_id" not in st.session_state:
    thread = client.beta.threads.create()
    st.session_state.thread_id = thread.id

# --- EVENT HANDLER FOR AGENT STREAMING ---
class StreamHandler(AssistantEventHandler):
    def __init__(self, container):
        super().__init__()
        self.container = container
        self.full_response = ""

    @override
    def on_text_delta(self, delta, snapshot):
        """Called when a piece of text is generated by the Agent."""
        self.full_response += delta.value
        self.container.markdown(self.full_response + "▌")

# --- SIDEBAR & UI ---
with st.sidebar:
    st.title("Settings")
    rag_enabled = st.toggle("Enable Agent (RAG)", value=False)
    if st.button("Clear Chat"):
        st.session_state.messages = []
        st.rerun()

st.title("🤖 Chatbot")

# Render history
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])

if prompt := st.chat_input("Ask me anything..."):
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    with st.chat_message("assistant"):
        response_placeholder = st.empty()
        
        if rag_enabled:
            # --- AGENT MODE (STREAMING) ---
            client.beta.threads.messages.create(
                thread_id=st.session_state.thread_id,
                role="user",
                content=prompt
            )
            
            handler = StreamHandler(response_placeholder)
            
            with client.beta.threads.runs.stream(
                thread_id=st.session_state.thread_id,
                assistant_id=ASSISTANT_ID,
                event_handler=handler,
            ) as stream:
                stream.until_done()
            
            full_response = handler.full_response
        else:
            # --- STANDARD MODE (STREAMING) ---
            full_response = ""
            stream = client.chat.completions.create(
                model="gpt-4o",
                messages=[{"role": m["role"], "content": m["content"]} for m in st.session_state.messages],
                stream=True,
            )
            for chunk in stream:
                if chunk.choices[0].delta.content:
                    full_response += chunk.choices[0].delta.content
                    response_placeholder.markdown(full_response + "▌")
        
        response_placeholder.markdown(full_response)
        st.session_state.messages.append({"role": "assistant", "content": full_response})
